version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: debtManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  debt_manager:
    container_name: debtmanager
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: debtmanagerapp:1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - "${CONTAINER_PORT}:${HOST_PORT}"
    depends_on:
      - postgres
